version: '3.8'

services:
  postgres-db-order:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiap-lanches-order
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-order:/var/lib/postgresql/data
    networks:
      - fiap-lanchonet-network

  fiap-lanches-order-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - fiap-lanches-order-api:/var/lib/fiaplancher/data
    depends_on:
      - postgres-db-order
    networks:
      - fiap-lanchonet-network

networks:
  fiap-lanchonet-network:
    external: true

volumes:
  postgres-db-order:
    driver: local
  fiap-lanches-order-api:
    driver: local