server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fiap-lanches-order}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.type.mapping: PaymentOrder:br.com.fiaplanchesorder.application.dtos.PaymentOrderDto

kafka:
  topic:
    name: fiap-lanches-payment
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
rest:
  clients:
    endpoint: http://localhost:8085/v1/client
  products:
    endpoint: http://localhost:8082/v1/product

