apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fiap-lanches-client-api
  name: fiap-lanches-client-api
  namespace: fiap-lanches-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-lanches-client-api
  template:
    metadata:
      labels:
        app: fiap-lanches-client-api
      name: fiap-lanches-client-api
    spec:
      containers:
        - image: docker.io/dalexandrias/fiap-lanches-client-app:latest
          imagePullPolicy: IfNotPresent
          name: fiap-lanches-client-api
          ports:
            - containerPort: 8085
              protocol: TCP
          envFrom:
            - configMapRef:
                name: fiap-lanches-client-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: fiap-lanches-client-secrets
                  optional: false
      restartPolicy: Always
