apiVersion: v1
kind: Service
metadata:
  name: fiap-lanches-api-node-port-svc
  namespace: fiap-lanches-api
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30005
  selector:
    app: fiap-lanches-client-api
  type: NodePort